### PR TITLE
fix AttributeError thrown by str.removeprefix when python < 3.9

### LINKED ISSUE #252: `removeprefix` is not compatible with Python 3.8
In configuration we use `str.removeprefix` which was added in Python 3.9 but `pinnwand` claims to be compatible with 3.8.

This wasn't caught because the code path is only used when an environment variable is passed which we don't do in tests.

- Add test for configuration through environment.
- Fix.

### PR DESCRIPTION
**Pull request by shtlrs**
Closes #252

Sorry for that, I forgot about the python 3.8 support.

### CODE REVIEW

**Comment by supakeen** [comment]
Thanks, interesting CI failures on this PR. I'll take a look at those.

**Comment by shtlrs** [comment]
It's due to where the patch is being made.

I know that patching has this kinds of gotchas however I'm using pytest's monkeypatch and rn idk really know why it's happening.

I'll have a proper look later on.

**Comment by shtlrs** [comment]
@supakeen It's fixed now.

I the problem lies within the design of the provider class.

During the test runtime/startup time, the `get_config` could be called  by some test, so the `_config` cls isntance is set, which mean s that it has already loaded the environment before the patching happens, and thus, all subsequent calls will use that class instance instead of making a fresh one & loading the patched env.

I opted for instantiation `Configuration` directly here since we're only testing something "trivial" and there's no application logic.

**Comment by supakeen** [comment]
Thanks yea, we can probably fix that issue when it's used by multiple tests and it becomes a chore.

**Pull request merged**
