### PR TITLE
Allow loading configuration from `.env` files.

### LINKED ISSUE #227: Load environment variables from `.env` file
Currently, `pinnwand` checks for environemnt variables that it loads to run the api, etc.

However, during development, it should be useful if these environment variables could be loaded up from a `.env` file.

This will help avoid issues such as committing files where config has been modified unintentionally.

### PR DESCRIPTION
**Pull request by shtlrs**
Closes #227 

The changes in this PR will now allow configuring pinnwand through a `.env` file.

The configuration in the `.env` file **will not** take precedence over its equivalent in the system's environment.

### CODE REVIEW

**Comment by shtlrs** [comment]
@supakeen I see the `test_use_shorter_uri` is failing because of the `clean_bd` fixture.

It's only used in one place, which seems a bit off since `test_use_longer_uri` is almost identical and isn't calling it.

Plus, why are you we clearing the tables if the database is destroyed later on along with its tempdirectory ?

I was thinking about completely deleting this, but wanted to double check first.

**Comment by supakeen** [comment]
Let's track these configuration issues in #232 for now. I'll take a look at these issues as well.

**Comment by shtlrs** [comment]
If #239 gets merged, I'll drop this one & make a new PR since the way we handle config will change.

**Comment by supakeen** [comment]
@shtlrs I've merged #239.

**Comment by shtlrs** [comment]
@supakeen I'll make a new PR to deal with the related issue.

**Pull request closed without merging**
