### PR TITLE
Add informational requests into json API

### PR DESCRIPTION
**Pull request by kapsh**
Little fanciness to allow api clients fetch available features.

### CODE REVIEW

**Comment by supakeen** [comment]
Will take a look-see at this one tomorrow as well. For now I notice lexers is plural yet expiry is singular in the routes?

**Comment by kapsh** [comment]
Agreed, changed this for consistency.

**Comment by kapsh** [comment]
Sorry, just checked and learned that "expiry" is uncountable word. I will leave it as is, but perhaps you will want to rename related methods later. Every day something new.

**Comment by supakeen** [comment]
This looks fine, can you please add a testcase for both these routes so I can merge them? A straightforward testcase would be to check if the count of expiries matches what is set in settings. Some examples of how to do testcases are already available in the test/ directory!

**Comment by kapsh** [comment]
These tests will check that api endpoints return the same data as utilities return.

**Comment by supakeen** [comment]
Perfect, thank you.

**Pull request merged**
